### ISSUE TITLE
Failure to run under docker: request to interface endpoint was not successful

### ISSUE THREAD

**Issue by DanTulovsky** [aauren/ntopng-exporter#11]
Hi,

With ntop-ng 6.1, on piOS, when running via docker:

```
❯ 01:16:58 PM  docker run --volume /home/dant/ntop-ng/exporter:/config --publish 3001:3001 aauren/ntopng-exporter
Config: ntopng:
        http://127.0.0.1:3000: 'admin'/*HIDDEN* - none - Allow Unsafe TLS? true
        Scrape Interval: 15s
        Scrape Targets: [all]

host:
        Interface List: [wlan0 tailscale0]

metric:
        Local Subnets: [192.168.86.0/24 224.0.0.0/4]
        Exclude DNS Metrics? false
        Serve:
                IP: 0.0.0.0
                Port: 3001

failed to cache interface ids: request to interface endpoint was not successful. Status: '0', Response: '[]'

```

I turned off authentication (and confirmed it's not required on ntop-ng).  Maybe 6.1 changed something?

Thank you
Dan

**Comment by aauren** [comment]
Yeah, by default docker containers will run in a separate network namespace. So you would need to run the container with `--net=host` if you want to access ntopng via the localhost IP. Otherwise, you could expose ntopng on the host's primary interface and configure ntopng-exporter to use that IP instead of localhost, that should work as well.

**Comment by aauren** [comment]
Ah yeah, that's the host's gateway address, but that should only work if ntopng is either configured to listen on that address or is configured to listen on all addresses (e.g. `0.0.0.0`). If ntopng is specifically relegated to just `127.0.0.1` for security reasons, then the docker bridge gateway would not work.
